In [324]:
#Task_1

import numpy as np

a = np.random.random((10, 3))
print(a)
a[np.arange(10), np.argmin(abs(a - 0.5), axis = 1)]

[[0.98748828 0.79207191 0.46139149]
 [0.4884195  0.80848667 0.56394351]
 [0.0191096  0.89787823 0.93441797]
 [0.91886186 0.40253207 0.42006948]
 [0.72209204 0.76971264 0.91193218]
 [0.99005161 0.36992748 0.35620054]
 [0.79593651 0.17904743 0.97024438]
 [0.79769003 0.91416005 0.84566049]
 [0.26735511 0.40547708 0.62065602]
 [0.4701458  0.43376879 0.38848856]]


array([0.46139149, 0.4884195 , 0.89787823, 0.42006948, 0.72209204,
       0.36992748, 0.79593651, 0.79769003, 0.40547708, 0.4701458 ])

In [279]:
#Task_2

import numpy as np

a=np.random.random((6, 6))
print(a)
print(a.sum(axis=1)/a.min(axis=0))

[[0.60334969 0.58702947 0.35225563 0.37220299 0.26132198 0.27409876]
 [0.74941176 0.03470373 0.51967131 0.16867784 0.54674629 0.98771921]
 [0.08173731 0.86458681 0.25970635 0.65469103 0.84912181 0.86413165]
 [0.85012311 0.2280628  0.76802596 0.85247647 0.47926597 0.18225359]
 [0.81777512 0.15431735 0.16524335 0.6199383  0.5491417  0.70859228]
 [0.27527223 0.07771974 0.34414636 0.98615161 0.69664529 0.88731795]]
[29.97723349 86.64573265 21.62855568 19.92086161 11.53752183 17.92696241]


In [338]:
#Task_3

import numpy as np

a = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 

i=0
while a[i]!=0:
    i+=1
    
max_el=a[i+1]
for j in range(i+1,len(a)):
    if a[j-1] == 0:
        if a[j]>max_el:
            max_el=a[j]
print(max_el)


5


In [323]:
#Task_4

import numpy as np

a = np.ones(10)
b = np.array([0, 1, 2, 3, 5, 5, 5, 8])
print(np.bincount(b))
print(a+np.pad(np.bincount(b),(0,len(a)-len(np.bincount(b))), 'constant'))


[1 1 1 1 0 3 0 0 1]
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [322]:
#Task_5

import numpy as np

a = np.arange(16).reshape(4, 4)
print(a)

d = {}
for i in range(len(a[0])):
    for j in range(len(a[0])):
        d[i+j]=[]
for i in range(len(a[0])):
    for j in range(len(a[0])):
        d[i+j].append(a[i,j])
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
{0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [7, 10, 13], 5: [11, 14], 6: [15]}


In [2]:
#Task_6

import numpy as np 
from scipy.cluster.vq import kmeans

def my_kmeans(A, k, it, epsilon): #n - размерность пространства, в котором берём точки
    i = 0  #счетчик
    N = A.shape[0]
    n = A.shape[1]
    C = A[:k, :] #начальные центроиды
    A = np.expand_dims(A, axis = 1) #увеличиваем размерность входной матрицы, теперь (N,1,n)
    C_new = np.zeros((k, n)) 
    Dist = k * N * n * np.max(A) ** 2
    Dist_new = 0
    while i < it or Dist_new - Dist > epsilon:
            Dist_new = Dist
            C_new = C
            D = A - C  
            qw = np.argmin((D ** 2).sum(axis = 2), axis = 1) #qw[номер элемента из входного массива]=количества элементов в соответствующем кластере
            S = np.zeros(N * n * k).reshape(N, k, n)
            S[np.arange(N), qw, :] = D[np.arange(N),  qw, :] / np.bincount(qw)[qw].reshape(N, 1) 
            C = C_new + np.squeeze(S.sum(axis = 0)) #теперь это центры масс кластеров
            qw = np.argmin(((A - C) ** 2).sum(axis = 2), axis = 1)
            S = np.zeros(N * n * k).reshape(N, k, n)
            S[np.arange(N), qw, :] = (A - C)[np.arange(N), qw, :]
            i = i + 1
            Dist = np.sqrt((S ** 2).sum(axis = 2)).sum(axis = 1).mean()  
    return C, Dist
           
Ar = np.genfromtxt('dataset-44970.csv', delimiter=',', skip_header=1)
Ar = Ar / np.std(Ar, axis = 0)

print(my_kmeans(Ar, 2, 1000, 1e-02))
print(kmeans(Ar, 2, 1000, 1e-02))

(array([[3.77111925, 5.90130403],
       [1.80133059, 4.02299172]]), 0.4704687987291571)
(array([[1.80133059, 4.02299172],
       [3.77111925, 5.90130403]]), 0.4701316241063735)
